// Canonical project records live here so every recruiter profile links to the
// same factual project page. Tailored profiles change selection and framing,
// never the underlying project history.
const majorProjects = [
  {
    slug: "detective-vision",
    title: "Detective Vision",
    eyebrow: "Cross-engine perception rendering",
    state: "Implemented — reusable reference build",
    cardSummary: "Selective-perception rendering built in both Unity and Unreal, with semantic masks, through-wall treatment and profiling hooks.",
    summary: "A dual-engine Technical Art reference implementation for selective-perception effects. The same semantic model is expressed through Unity 6 URP Render Graph and Unreal Engine 5.6 CustomDepth/Stencil plus RDG, while each engine keeps the rendering path that best fits its native pipeline.",
    visual: "rendering",
    visualLabels: ["Classify", "Resolve occlusion", "Composite"],
    image: "assets/projects/detective-vision-unity-arkham.webp",
    imageAlt: "Unity 6 reference lab running the Arkham-inspired Detective Vision profile with semantic targets visible through occluding geometry.",
    imageCaption: "Unity / Arkham-inspired profile",
    role: "Sole developer — rendering architecture, shaders, engine integration, benchmark lab and technical documentation.",
    tools: ["Unity 6.3", "URP 17.3", "C#", "ShaderLab", "Unreal Engine 5.6", "C++", "HLSL", "RDG"],
    tags: ["technical-art", "rendering", "shader", "unity", "unreal", "profiling", "tooling", "c++", "hlsl"],
    highlights: [
      "Six semantic target categories share one gameplay-facing model while presentation changes between Arkham-, Witcher-, Hitman- and custom-authored profiles.",
      "Unity builds a full-resolution semantic mask and target depth, then adds the Witcher organic contour at half resolution before the final composite.",
      "Unreal maps the same categories through CustomDepth/CustomStencil, a Scene View Extension and RDG passes, including optional alternate representations.",
    ],
    evidence: [
      "Reusable Unity package and Unreal plugin are separated from their reference-lab, benchmark and diagnostics projects.",
      "Both demos include a 0 / 10 / 50 / 100 / 250 / 500 / 1000-target benchmark ladder and engine-specific profiling markers.",
      "The repository documentation covers architecture, cross-engine mapping, porting, profiling and a beginner-oriented source walkthrough.",
    ],
    boundary: "The project includes a reproducible profiling workflow and capture template, but no controlled benchmark table is presented yet. HUD timings remain diagnostic rather than being claimed as isolated pass costs.",
    mediaIntro: "The full capture set shows the same semantic model across Unity and Unreal, including disabled baselines, authored profiles, occlusion behaviour and the 1000-target stress configuration.",
    media: [
      {
        src: "assets/projects/detective-vision-unreal-off-benchmark.webp",
        alt: "Unreal Engine Detective Vision reference lab with the effect disabled while the 1000-target benchmark population is active.",
        caption: "Unreal / disabled / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unreal-arkham-benchmark.webp",
        alt: "Unreal Engine reference lab running the Arkham-inspired profile with the 1000-target benchmark population enabled.",
        caption: "Unreal / Arkham / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unreal-witcher-benchmark.webp",
        alt: "Unreal Engine reference lab running the Witcher-inspired contour treatment under the 1000-target benchmark load.",
        caption: "Unreal / Witcher / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unreal-hitman-benchmark.webp",
        alt: "Unreal Engine reference lab running the Hitman-inspired treatment under the 1000-target benchmark load.",
        caption: "Unreal / Hitman / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unreal-custom-benchmark.webp",
        alt: "Unreal Engine reference lab running the custom semantic profile under the 1000-target benchmark load.",
        caption: "Unreal / Custom / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unreal-off.webp",
        alt: "Unreal Engine reference lab with Detective Vision disabled for a clean baseline comparison.",
        caption: "Unreal / disabled baseline",
      },
      {
        src: "assets/projects/detective-vision-unreal-arkham.webp",
        alt: "Unreal Engine reference lab showing the Arkham-inspired semantic rendering profile.",
        caption: "Unreal / Arkham profile",
      },
      {
        src: "assets/projects/detective-vision-unreal-witcher.webp",
        alt: "Unreal Engine reference lab showing the Witcher-inspired contour rendering profile.",
        caption: "Unreal / Witcher profile",
      },
      {
        src: "assets/projects/detective-vision-unreal-hitman.webp",
        alt: "Unreal Engine reference lab showing the Hitman-inspired selective-perception profile.",
        caption: "Unreal / Hitman profile",
      },
      {
        src: "assets/projects/detective-vision-unreal-custom.webp",
        alt: "Unreal Engine reference lab showing the custom semantic rendering profile.",
        caption: "Unreal / Custom profile",
      },
      {
        src: "assets/projects/detective-vision-unity-off.webp",
        alt: "Unity 6 reference lab with Detective Vision disabled for a clean baseline comparison.",
        caption: "Unity / disabled baseline",
      },
      {
        src: "assets/projects/detective-vision-unity-witcher.webp",
        alt: "Unity 6 reference lab showing the Witcher-inspired contour rendering profile.",
        caption: "Unity / Witcher profile",
      },
      {
        src: "assets/projects/detective-vision-unity-witcher-occlusion.webp",
        alt: "Unity 6 reference lab showing the Witcher-inspired contour profile through the lab occluders.",
        caption: "Unity / Witcher occlusion check",
      },
      {
        src: "assets/projects/detective-vision-unity-hitman.webp",
        alt: "Unity 6 reference lab showing the Hitman-inspired selective-perception profile.",
        caption: "Unity / Hitman profile",
      },
      {
        src: "assets/projects/detective-vision-unity-custom.webp",
        alt: "Unity 6 reference lab showing the custom semantic rendering profile.",
        caption: "Unity / Custom profile",
      },
      {
        src: "assets/projects/detective-vision-unity-off-benchmark.webp",
        alt: "Unity 6 reference lab with the effect disabled while the 1000-target benchmark population is active.",
        caption: "Unity / disabled / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unity-arkham-benchmark.webp",
        alt: "Unity 6 reference lab running the Arkham-inspired profile under the 1000-target benchmark load.",
        caption: "Unity / Arkham / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unity-witcher-benchmark.webp",
        alt: "Unity 6 reference lab running the Witcher-inspired contour profile under the 1000-target benchmark load.",
        caption: "Unity / Witcher / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unity-hitman-benchmark.webp",
        alt: "Unity 6 reference lab running the Hitman-inspired profile under the 1000-target benchmark load.",
        caption: "Unity / Hitman / +1000 targets",
      },
      {
        src: "assets/projects/detective-vision-unity-custom-benchmark.webp",
        alt: "Unity 6 reference lab running the custom semantic profile under the 1000-target benchmark load.",
        caption: "Unity / Custom / +1000 targets",
      },
    ],
    manualRelated: ["jam-ta-tools", "hydroflow", "graph-calculator"],
    public: true,
  },
  {
    slug: "jam-ta-tools",
    title: "JAM TA Tools",
    eyebrow: "Cross-DCC pipeline suite",
    state: "Implemented",
    cardSummary: "A production evidence loop from Blender or Maya validation to engine-side verification.",
    summary: "A cross-DCC technical-art pipeline in which Blender and Maya adapters measure assets, a shared Python core interprets production rules, sidecars preserve export evidence, and Unity and Unreal verify what the engines actually imported.",
    visual: "pipeline",
    visualLabels: ["DCC measure", "Rules interpret", "Engine verify"],
    image: "assets/projects/jam-ta-tools-blender-validation.webp",
    imageAlt: "Blender viewport showing a character asset beside the JAM TA Tools validation and export panel, including a production-budget warning.",
    imageCaption: "Blender / validation panel",
    sourcePreview: {
      language: "Python",
      file: "Common/jam_ta_core/rules.py",
      lines: [
        "    for rule_id, callback in tuple(_RULES.items()):",
        "        try:",
        "            issues = _coerce_issues(rule_id, callback(report, profile, context))",
        "        except Exception as exc:",
        "            issues = [ValidationIssue(",
        "                rule_id=\"extension.{0}.exception\".format(rule_id),",
        "                title=\"Custom validation rule failed\",",
        "                message=\"Rule '{0}' raised {1}: {2}\".format(rule_id, type(exc).__name__, exc),",
        "                category=\"Pipeline\",",
        "                severity=\"ERROR\",",
      ],
    },
    role: "Sole developer — architecture, DCC adapters, validation core, export evidence and engine bridges.",
    tools: ["Python", "Blender API", "Maya API", "PySide6", "Unity", "Unreal Engine", "C#", "C++"],
    tags: ["technical-art", "pipeline", "tooling", "validation", "unity", "unreal", "dcc"],
    highlights: [
      "Asset validation covering geometry, UVs, texel density, materials, LODs, collision, sockets and modular-grid rules.",
      "Versioned .jammeta.json sidecars connect DCC measurements to what Unity and Unreal actually receive.",
      "Headless JSON and JUnit output make the shared validation core suitable for CI rather than only artist-side inspection.",
    ],
    evidence: [
      "24 shared-core unit tests passed.",
      "Python sources across Blender, Maya and the shared core passed syntax compilation.",
      "The source includes verification bridges for both Unity and Unreal.",
    ],
    boundary: "The strongest missing evidence is a short end-to-end capture of one asset moving through a DCC and into an engine, including a discrepancy caught after import.",
    repository: "https://github.com/J4ck4b14/Tools",
    mediaIntro: "The captures show the same validation philosophy in both DCC environments: measure the asset where artists work, surface production rules there, and preserve evidence for engine-side verification.",
    media: [
      {
        src: "assets/projects/jam-ta-tools-maya-scene-validation.webp",
        alt: "Maya scene using JAM TA Tools panels to inspect and validate production data.",
        caption: "Maya / scene validation",
      },
      {
        src: "assets/projects/jam-ta-tools-maya-modular-validation.webp",
        alt: "Maya viewport showing a modular asset set with JAM TA Tools validation and production controls.",
        caption: "Maya / modular asset validation",
      },
    ],
    manualRelated: ["detective-vision", "hydroflow", "mapdesigner", "protomake"],
    public: true,
  },
  {
    slug: "infinity",
    title: "Infinity",
    eyebrow: "Systemic world simulation",
    state: "Research build — active development",
    cardSummary: "A deterministic ecology where terrain, water, climate, flora and fauna form readable causal chains.",
    summary: "A Unity 6 systemic-world simulation built around causality rather than disconnected random generation. Geography shapes water; water and climate shape plant viability; persistent biomass supports animals; grazing changes the state later agents inherit.",
    visual: "ecosystem",
    visualLabels: ["Terrain + water", "Flora + biomass", "Fauna + residue"],
    image: "assets/projects/infinity-relative-twi.webp",
    imageAlt: "Unity editor diagnostic view of Infinity terrain with a dense terrain and drainage diagnostic overlay tracing structure across the generated landscape.",
    imageCaption: "World diagnostic / terrain + drainage",
    sourcePreview: {
      language: "C# / Unity 6",
      file: "World/Ecology/EcologySimulator.cs",
      lines: [
        "            RepairLegacyClockResidue(floraState, faunaState);",
        "            double targetTimeDays = floraState.SimulationTimeDays + deltaDays;",
        "            float remaining = deltaDays;",
        "",
        "            while (remaining > 0.000001f)",
        "            {",
        "                float dt = Mathf.Min(2f, remaining);",
        "                movementBackend.Step(geography, floraState, faunaState, faunaSettings, dt);",
        "                FloraSimulator.Step(floraPotential, floraGenerationSettings, floraState, floraSimulationSettings, dt);",
        "                movementBackend.RefreshAllForage(floraState);",
      ],
    },
    role: "Sole developer and designer — simulation architecture, procedural systems, diagnostics and presentation.",
    tools: ["Unity 6", "C#", "Entities", "Burst", "Unity Mathematics", "ShaderLab", "URP"],
    tags: ["simulation", "procedural", "systems", "ecology", "hydrology", "unity", "data-visualization"],
    highlights: [
      "Deterministic geography, priority-flood hydrology, basins, contributing area and channel candidates.",
      "Persistent flora biomass and deer agents with terrain-constrained movement, forage perception, herding and physiology.",
      "Dedicated diagnostic views expose geography, hydrology, climate, ground, flora, ecology and fauna state.",
    ],
    evidence: [
      "The current project documents 80 EditMode test cases.",
      "The repository contains the project structure, pinned package versions, system source and test source.",
      "The current architecture separates simulation from presentation.",
    ],
    boundary: "Predation, reproduction, people and social systems are intended later layers; this page does not present them as implemented features.",
    repository: "https://github.com/J4ck4b14/InfinityProject",
    mediaIntro: "Infinity exposes intermediate world state instead of hiding the simulation behind a final beauty shot. These captures cover terrain, drainage, ground, climate and flora authoring/diagnostic views.",
    media: [
      {
        src: "assets/projects/infinity-world-diagnostic-01.webp",
        alt: "Unity editor capture of an Infinity world diagnostic overlay across the generated terrain.",
        caption: "World diagnostic / view 01",
      },
      {
        src: "assets/projects/infinity-world-diagnostic-02.webp",
        alt: "Unity editor capture showing another Infinity terrain and environmental diagnostic layer.",
        caption: "World diagnostic / view 02",
      },
      {
        src: "assets/projects/infinity-world-diagnostic-04.webp",
        alt: "Unity editor capture showing a terrain-wide Infinity diagnostic layer.",
        caption: "World diagnostic / view 04",
      },
      {
        src: "assets/projects/infinity-world-diagnostic-05.webp",
        alt: "Unity editor capture showing environmental state across the Infinity terrain.",
        caption: "World diagnostic / view 05",
      },
      {
        src: "assets/projects/infinity-world-diagnostic-06.webp",
        alt: "Unity editor capture showing another environmental diagnostic across the Infinity world.",
        caption: "World diagnostic / view 06",
      },
      {
        src: "assets/projects/infinity-world-diagnostic-07.webp",
        alt: "Unity editor capture showing a world-state diagnostic overlay across the Infinity terrain.",
        caption: "World diagnostic / view 07",
      },
      {
        src: "assets/projects/infinity-world-diagnostic-08.webp",
        alt: "Unity editor capture using a high-contrast diagnostic palette to expose world-state variation.",
        caption: "World diagnostic / view 08",
      },
      {
        src: "assets/projects/infinity-world-diagnostic-09.webp",
        alt: "Unity editor capture using a high-contrast diagnostic overlay across the generated world.",
        caption: "World diagnostic / view 09",
      },
      {
        src: "assets/projects/infinity-flora-tool.webp",
        alt: "Infinity Flora Tool controls for species response profiles and environment-driven viability parameters.",
        caption: "Flora authoring controls",
      },
      {
        src: "assets/projects/infinity-ground-conditions-tool.webp",
        alt: "Infinity Ground Conditions Tool controls used to generate and inspect terrain-derived ground state.",
        caption: "Ground conditions controls",
      },
      {
        src: "assets/projects/infinity-climate-tool.webp",
        alt: "Infinity Climate Tool controls for temperature, precipitation, wind and related environmental inputs.",
        caption: "Climate authoring controls",
      },
    ],
    manualRelated: ["protomake", "mapdesigner", "hydroflow", "jam-ta-tools"],
    public: true,
  },
  {
    slug: "hydroflow",
    title: "HydroFlow",
    eyebrow: "Terrain-bound river authoring",
    state: "Unity package v0.4.0 — active development",
    cardSummary: "A terrain-aware river tool that solves and bakes expensive flow work in the editor, then keeps runtime water deliberately cheap.",
    summary: "A Unity 6.3 river-authoring package built around a production rule: expensive terrain, route and shallow-water work belongs in the editor. Authored curves act as plan-view intent guides; the generated river grounds itself to terrain, can carve a depth-aware channel, bakes versioned flow fields and leaves runtime rendering and interactions lightweight.",
    visual: "hydro",
    visualLabels: ["Ground route", "Bake flow", "Render cheaply"],
    image: "assets/projects/hydroflow-river-perspective.webp",
    imageAlt: "Unity scene view showing a terrain-bound HydroFlow river running from foreground toward a mountain landscape.",
    imageCaption: "Terrain-bound river / perspective",
    role: "Sole developer — authoring workflow, grounding solver, terrain integration, flow bake, diagnostics and runtime material approach.",
    tools: ["Unity 6.3", "C#", "URP", "ShaderLab", "Splines", "Render Textures", "NUnit", "Unreal Blueprints"],
    tags: ["technical-art", "water", "tooling", "shader", "unity", "unreal", "optimization", "terrain"],
    highlights: [
      "Terrain-bound authoring treats spline height as an intent guide, rejects physically implausible routes and can offer tested reverse or lateral alternatives instead of silently forcing a result.",
      "Adaptive surface geometry separates dense terrain/flow analysis from visible mesh density, while depth-aware automatic carving works from a preserved source TerrainData copy.",
      "Versioned RGBAHalf flow bakes store velocity, depth and rapid potential with source signatures; runtime shaders and water interactors consume the baked result without solving shallow water in Play Mode.",
    ],
    evidence: [
      "The supplied package identifies itself as HydroFlow 0.4.0 for Unity 6000.3.5f2.",
      "Nine EditMode tests across grounding, adaptive mesh generation, bake assets and source-signature invalidation are included.",
      "HydroFlow Studio exposes scene-wide rebuild, stale-bake and diagnostic workflows, while the included captures show grounded river routes on terrain.",
    ],
    boundary: "The Unreal side remains a Blueprint-first bridge specification rather than a compiled plugin, and the supplied captures focus on authoring evidence rather than a final runtime beauty pass.",
    mediaIntro: "The captures focus on the authored result in terrain: spline-driven river placement, terrain following and the readable path of the water through the landscape.",
    media: [
      {
        src: "assets/projects/hydroflow-terrain-river-overview.webp",
        alt: "Unity scene view showing HydroFlow river geometry following terrain across a broader landscape view.",
        caption: "Terrain river / overview",
      },
    ],
    manualRelated: ["detective-vision", "jam-ta-tools", "mapdesigner", "infinity"],
    public: true,
  },
  {
    slug: "protomake",
    title: "ProtoMake",
    eyebrow: "Browser-native 2D engine & editor",
    state: "Implemented — actively evolving",
    cardSummary: "A TypeScript runtime and visual editor built for fast, portable 2D production.",
    summary: "A browser-native 2D engine and visual editor spanning authoring, rendering, physics, scripting, behaviour graphs, animation, audio, UI, persistence, profiling and deterministic export foundations.",
    visual: "engine",
    visualLabels: ["Author", "Play + inspect", "Export"],
    image: "assets/projects/protomake-editor.webp",
    imageAlt: "ProtoMake browser editor showing a 2D project scene, hierarchy, inspector, console and authoring controls.",
    imageCaption: "Editor / authoring view",
    role: "Sole developer — product direction, runtime, editor architecture, tooling, validation and example content.",
    tools: ["TypeScript", "Vite", "PixiJS", "Rapier 2D", "Zod", "IndexedDB", "Vitest"],
    tags: ["engine", "tooling", "editor", "typescript", "physics", "serialization", "testing"],
    highlights: [
      "Package-separated runtime, renderer, physics, scripting, UI, persistence, animation, audio and editor layers.",
      "Durable GUID identity, schema migrations, isolated play-mode state and deterministic interchange foundations.",
      "Static, mixed and dynamic lighting, shadow casters, profiles, save slots, achievements and runtime inspection.",
    ],
    evidence: ["31 test files and 141 tests passed.", "Type-check, lint, formatting and package-boundary checks passed.", "Editor, standalone player and showcase production builds completed."],
    boundary: "The repository is still published under its former Forge name; that public identity should be renamed or redirected before promotion.",
    repository: "https://github.com/J4ck4b14/Forge",
    mediaIntro: "The two captures deliberately pair authoring and runtime: the editor is the product, but the player view shows that the authored scene survives outside the editing workspace.",
    media: [
      {
        src: "assets/projects/protomake-player.webp",
        alt: "ProtoMake player view running a small authored 2D scene outside the main editor workspace.",
        caption: "Runtime / player view",
      },
    ],
    manualRelated: ["mapdesigner", "jam-ta-tools", "graph-calculator"],
    public: true,
  },
  {
    slug: "mapdesigner",
    title: "MapDesigner",
    eyebrow: "Spatial technical-design application",
    state: "Substantial active development",
    cardSummary: "A C++/Qt desktop tool for staging, analysing and handing off gameplay spaces.",
    summary: "A C++20 and Qt desktop application for architectural greyboxing, multi-storey spatial authoring, encounter staging, route analysis and clean handoff into Unity and Unreal.",
    visual: "spatial",
    visualLabels: ["Author space", "Analyse play", "Engine handoff"],
    image: "assets/projects/mapdesigner-plan-analysis.webp",
    imageAlt: "MapDesigner desktop application showing a plan view with authored spatial layout and analysis overlays.",
    imageCaption: "Plan view / spatial analysis",
    role: "Sole developer — application architecture, authoring UX, spatial analysis and engine import paths.",
    tools: ["C++20", "Qt", "CMake", "Unity 6", "Unreal Engine 5.6"],
    tags: ["technical-design", "tooling", "c++", "spatial", "analysis", "unity", "unreal"],
    highlights: ["Multi-storey greyboxing with routes, patrols, timelines and field-of-view review.", "Spatial-analysis tools turn map geometry into design evidence.", "Replaceable generated ownership layers keep Unity and Unreal imports safe to refresh."],
    evidence: ["The project contains approximately 27,000 source, test and integration lines.", "Thirteen CTest targets and 72 explicit assertions are present.", "Packaged Windows release and test executables are included."],
    boundary: "The packaged Windows build still needs a current public demonstration and a reproducible clean-build record.",
    mediaIntro: "The same authored space can be inspected from design, elevation and 3D perspectives, keeping analysis tied to the geometry that produced it.",
    media: [
      {
        src: "assets/projects/mapdesigner-elevation-view.webp",
        alt: "MapDesigner showing an elevation or side view of the authored level geometry.",
        caption: "Elevation / side view",
      },
      {
        src: "assets/projects/mapdesigner-3d-preview.webp",
        alt: "MapDesigner showing a three-dimensional preview of the authored level volume.",
        caption: "3D spatial preview",
      },
      {
        src: "assets/projects/mapdesigner-plan-authoring.webp",
        alt: "MapDesigner showing the authored plan layout with editor controls and analysis panels.",
        caption: "Plan authoring",
      },
    ],
    manualRelated: ["protomake", "jam-ta-tools", "graph-calculator"],
    public: true,
  },
  {
    slug: "return-vector",
    title: "Return Vector",
    eyebrow: "Focused combat prototype",
    state: "Playable prototype — built in under a week",
    cardSummary: "A one-weapon combat system where every throw creates commitment, positioning pressure and a dangerous return path.",
    summary: "A top-down Unity combat prototype centred on one persistent thrown weapon. Outbound flight, surface response, player repositioning and recall-line damage create a compact possibility space rather than a list of unrelated abilities.",
    visual: "combat",
    visualLabels: ["Throw", "Reposition", "Recall"],
    image: "assets/projects/return-vector-warden.webp",
    imageAlt: "Return Vector gameplay during the Return Warden boss encounter, with the player, weapon path, arena hazards and boss health bar visible.",
    imageCaption: "Boss encounter / Return Warden",
    role: "Sole developer and designer — combat, AI, encounters, presentation and testing.",
    tools: ["Unity 6", "C#", "A* Pathfinding", "Unity Test Framework"],
    tags: ["gameplay", "combat", "systems", "unity", "ai", "game-feel"],
    highlights: ["Explicit outbound and recall state machines for one persistent weapon.", "Deterministic surface responses and recall-line damage make positioning readable.", "Enemy roles, difficulty levels and the Return Warden escalate the same core rule set."],
    evidence: ["Fifteen EditMode test files are present.", "The project contains approximately 19,700 lines of C#.", "The implementation and scope support the documented under-one-week constraint."],
    boundary: "A public build and a fresh Unity Test Runner report are still missing.",
    mediaIntro: "The captures show the prototype as a complete playable loop rather than only its weapon mechanic: level layout, difficulty selection, combat, boss escalation and run completion.",
    media: [
      {
        src: "assets/projects/return-vector-level-layout.webp",
        alt: "Unity scene view showing the Return Vector combat spaces and encounter layout.",
        caption: "Level layout / editor",
      },
      {
        src: "assets/projects/return-vector-difficulty-select.webp",
        alt: "Return Vector difficulty-selection screen before entering a run.",
        caption: "Difficulty selection",
      },
      {
        src: "assets/projects/return-vector-combat-01.webp",
        alt: "Return Vector gameplay showing the player and persistent thrown weapon during combat.",
        caption: "Combat / outbound weapon",
      },
      {
        src: "assets/projects/return-vector-combat-02.webp",
        alt: "Return Vector gameplay showing positioning around the weapon return path.",
        caption: "Combat / recall positioning",
      },
      {
        src: "assets/projects/return-vector-win-summary.webp",
        alt: "Return Vector win screen summarising a completed run.",
        caption: "Run completion",
      },
    ],
    manualRelated: ["dungeon-crawler", "multishooter", "the-cave"],
    public: true,
  },
  {
    slug: "arsenal-ar-card",
    title: "ARsenal",
    eyebrow: "AR business card & survival game",
    state: "Functional core — final content incomplete",
    cardSummary: "A two-sided physical card that launches a professional AR profile and a compact survival game.",
    summary: "A marker-based mobile AR project whose front image launches an interactive professional profile and whose back image launches a small tank-based survival game with enemies, waves, procedural cover and persistent progression.",
    visual: "xr",
    visualLabels: ["Scan marker", "Place content", "Play"],
    role: "Sole developer and designer — AR flow, mobile interaction, gameplay systems and physical-card concept.",
    tools: ["Unity 6", "C#", "AR Foundation", "ARCore", "Input System", "URP", "Shader Graph"],
    tags: ["ar", "xr", "mobile", "unity", "gameplay", "interaction"],
    highlights: ["Separate tracked-image experiences for the card front and back.", "Touch-driven survival gameplay with enemies, projectiles, waves, shields and procedural cover.", "JSON persistence and custom physical marker artwork connect the printed object to the runtime."],
    evidence: ["The project contains both tracked-image and gameplay architecture.", "Front and back marker art plus original 3D assets are present.", "The project targets Android and uses current AR Foundation event patterns."],
    boundary: "The final front-side media, CV destination and polished on-device demonstration still need to be completed.",
    repository: "https://github.com/J4ck4b14/BusinessCard_ARsenal",
    manualRelated: ["sefei-vr-hospital", "multishooter", "return-vector"],
    public: true,
  },
  {
    slug: "sefei-vr-hospital",
    title: "SEFEi VR Hospital Training",
    eyebrow: "Immersive healthcare training",
    state: "Implemented — visual case study",
    cardSummary: "A guided VR simulation of sterile hospital-pharmacy preparation workflows.",
    summary: "A VR training experience for vocational Farmacotecnia students, created for Hospital Universitario de Fuenlabrada with UFV and IES Salvador Allende. It guides learners through sterile clothing, ingredient preparation, controlled-room progression, lab procedures and final evaluation.",
    visual: "xr",
    visualLabels: ["Prepare", "Perform", "Validate"],
    image: "assets/projects/sefei-vr-interaction.webp",
    imageAlt: "First-person VR hospital training view showing a tracked hand, controller guidance and an interaction prompt.",
    imageCaption: "VR interaction / training flow",
    role: "Sole developer — Unreal Blueprint implementation, interaction design, workflow simulation and environment integration.",
    tools: ["Unreal Engine 5.4", "Blueprints", "SteamVR", "Meta Quest 2"],
    tags: ["vr", "xr", "training", "unreal", "interaction", "serious-game"],
    highlights: ["Ordered sterile-clothing and preparation-tray workflow.", "Pass-through chamber, pressure airlock and vertical-flow cabinet interactions.", "Labelling, validation, cleaning and persistent evaluation feedback."],
    evidence: ["The supplied project trailer shows the experience running in first-person VR across onboarding, sterile preparation and laboratory interactions.", "Project records identify the audience, workflow, platforms and sole-development role.", "The client and project partners may be named publicly."],
    boundary: "The source project is not currently accessible, so the page remains a visual case study and avoids claims that depend on fresh source verification.",
    mediaIntro: "The trailer is the strongest surviving evidence of the complete experience, so the page treats it as a visual case study rather than reconstructing source-level claims.",
    video: {
      src: "assets/projects/sefei-vr-hospital-trailer.mp4",
      poster: "assets/projects/sefei-vr-interaction.webp",
      caption: "Project trailer / 1 min 55 s"
    },
    media: [
      {
        src: "assets/projects/sefei-vr-clothing.webp",
        alt: "VR interface asking the learner to select sterile clothing items in the correct order.",
        caption: "Sterile clothing sequence"
      },
      {
        src: "assets/projects/sefei-vr-cabinet.webp",
        alt: "VR view inside a vertical-flow cabinet during a medication preparation interaction.",
        caption: "Vertical-flow cabinet interaction"
      }
    ],
    manualRelated: ["arsenal-ar-card", "detective-vision", "jam-ta-tools", "multishooter"],
    public: true,
  },
  {
    slug: "dungeon-crawler",
    title: "DungeonCrawler",
    eyebrow: "C++ terminal roguelike",
    state: "Complete — publicly playable",
    cardSummary: "A C++20 roguelike with procedural topology, reactive defence and persistent Legacy progression.",
    summary: "A terminal roguelike written from scratch in C++20, combining procedural dungeon topology, input-driven defence, equipment and status systems, persistent Legacy progression, a persistent bestiary and native plus WebAssembly targets.",
    visual: "terminal",
    visualLabels: ["Generate", "Survive", "Persist"],
    role: "Sole developer — architecture, procedural design, combat, persistence and browser platform layer.",
    tools: ["C++20", "CMake", "Emscripten", "WebAssembly", "CTest"],
    tags: ["c++", "roguelike", "procedural", "gameplay", "systems", "webassembly"],
    highlights: ["Seedable procedural topology with validation reporting.", "Reactive combat, breaching, perception, equipment, loot, relics and statuses.", "Native profile storage plus a browser bridge for the public build."],
    evidence: ["The current source compiles under C++20.", "The regression executable completes with all tests passing.", "A browser-playable itch.io build is public."],
    repository: "https://github.com/J4ck4b14/DungeonCrawler",
    live: "https://jackofaltrades.itch.io/dungeoncrawler",
    boundary: "The browser build is keyboard-led and terminal-based; it demonstrates game systems rather than visual presentation.",
    manualRelated: ["infinity", "return-vector", "the-cave"],
    public: true,
  },
  {
    slug: "fishyfish",
    title: "FishyFish",
    eyebrow: "Online co-op systemic adventure",
    state: "Team project — active development",
    cardSummary: "A persistent two-player world with shared progression, faction memory and networked authored content.",
    summary: "An online cooperative project built around a persistent two-player pair. Shared history, progression, currency and systemic faction consequences connect authored jobs, exploration, stealth, puzzles and narrative decisions across multiple scenes.",
    visual: "network",
    visualLabels: ["Connect", "Share state", "Remember"],
    image: "assets/projects/fishyfish-city-character-lineup.webp",
    imageAlt: "FishyFish city scene showing the stylised fish characters, clothing pieces and graffiti-covered brick environment.",
    imageCaption: "City scene / character presentation",
    role: "Lead developer and primary implementer; initially responsible for multiplayer connectivity and later for the broader game architecture and content. Original collaborators remain credited.",
    tools: ["Unity 6", "C#", "Netcode for GameObjects", "Unity Relay", "Cinemachine", "AI Navigation", "UI Toolkit"],
    tags: ["multiplayer", "networking", "unity", "systems", "ai", "narrative", "co-op"],
    highlights: ["Relay and IP session paths with approval, authentication and reconnect handling.", "Versioned shared saves, pair identity, currency, progression and backstory-derived hidden statistics.", "Faction heat, influence and incident memory across networked jobs, puzzles, cinematics and scene flow."],
    evidence: ["The project contains nine scenes and 143 gameplay or editor scripts.", "The networking, shared progression and systemic architecture are present in source.", "Project credits preserve the original collaborators while identifying Juan as lead developer and primary implementer."],
    boundary: "The project needs synchronized two-client footage and a current working-path audit before it becomes a primary recruiter case study.",
    manualRelated: ["multishooter", "infinity", "return-vector"],
    public: true,
  },
  {
    slug: "graph-calculator",
    title: "Graph Calculator",
    eyebrow: "Technical-design desktop laboratory",
    state: "Implemented",
    cardSummary: "Four connected workspaces for mathematics, curves, game economies and live HLSL.",
    summary: "A .NET 8 WPF design laboratory connecting mathematical visualisation, visual curve authoring, stochastic game-economy simulation and live HLSL compilation under one evidence-focused desktop workflow.",
    visual: "graph",
    visualLabels: ["Model", "Simulate", "Export"],
    image: "assets/projects/graph-calculator-complex-domain.webp",
    imageAlt: "Graph Calculator visualising a complex-domain function as a colour field inside its desktop graphing workspace.",
    imageCaption: "Complex-domain visualisation",
    role: "Sole developer — parsers, numerical systems, economy simulation, shader workflow and desktop UX.",
    tools: ["C#", ".NET 8", "WPF", "XAML", "HLSL", "Direct3D interop"],
    tags: ["technical-design", "desktop", "simulation", "hlsl", "data-visualization", "tooling"],
    highlights: ["2D/3D, parametric, implicit, vector and scalar mathematical workspaces.", "Curve authoring plus stochastic economy simulation, cohorts, predictions, balance search and replay.", "Direct HLSL editing and compilation with engine-oriented export paths."],
    evidence: ["The project contains approximately 19,000 lines of C#.", "A Windows debug executable and DLL set are present.", "One example economy project establishes the intended design workflow."],
    boundary: "The four workspaces need one coherent recorded workflow and focused parser/simulation tests to avoid reading as an unrelated feature list.",
    repository: "https://github.com/J4ck4b14/Graph-Calculator",
    mediaIntro: "The application spans several mathematical and technical-design workspaces. The gallery keeps that breadth visible rather than reducing the project to a single graph.",
    media: [
      {
        src: "assets/projects/graph-calculator-parametric-2d.webp",
        alt: "Graph Calculator showing a two-dimensional parametric curve and its authoring controls.",
        caption: "2D parametric graph",
      },
      {
        src: "assets/projects/graph-calculator-3d-points.webp",
        alt: "Graph Calculator showing a three-dimensional graph workspace with plotted data.",
        caption: "3D point / scalar view",
      },
      {
        src: "assets/projects/graph-calculator-surface.webp",
        alt: "Graph Calculator showing a rendered three-dimensional mathematical surface.",
        caption: "3D surface",
      },
      {
        src: "assets/projects/graph-calculator-vector-field.webp",
        alt: "Graph Calculator showing a two-dimensional vector-field visualisation.",
        caption: "Vector field",
      },
      {
        src: "assets/projects/graph-calculator-curve.webp",
        alt: "Graph Calculator showing a piecewise authored curve in the graph workspace.",
        caption: "Authored curve",
      },
      {
        src: "assets/projects/graph-calculator-parametric-3d.webp",
        alt: "Graph Calculator showing multiple parametric curves in the three-dimensional workspace.",
        caption: "3D parametric curves",
      },
      {
        src: "assets/projects/graph-calculator-complex-domain-alt.webp",
        alt: "Graph Calculator showing a second complex-domain colour-field visualisation.",
        caption: "Complex-domain alternate view",
      },
      {
        src: "assets/projects/graph-calculator-analysis-view.webp",
        alt: "Graph Calculator showing multiple plotted curves alongside a larger parametric graph.",
        caption: "Multi-graph analysis",
      },
      {
        src: "assets/projects/graph-calculator-economy-designer.webp",
        alt: "Graph Calculator Economy Designer showing a node-based game-economy model and simulation controls.",
        caption: "Economy Designer",
      },
    ],
    manualRelated: ["mapdesigner", "protomake", "la-cocina-del-groumet"],
    public: true,
  },
  {
    slug: "la-cocina-del-groumet",
    title: "La Cocina del Groumet",
    eyebrow: "Self-hosted recipe platform",
    state: "Deployed full-stack V1",
    cardSummary: "A Raspberry Pi-hosted recipe community with moderation, image processing and privacy-aware operations.",
    summary: "A recipe-discovery and submission platform that grew from a static exercise into a self-hosted application with relational storage, image processing, moderation, security controls, privacy-conscious logging and private administration.",
    visual: "web",
    visualLabels: ["Submit", "Moderate", "Serve"],
    role: "Sole developer — frontend, PHP API, database, moderation, security and Raspberry Pi operations.",
    tools: ["HTML", "CSS", "JavaScript", "PHP 8", "MariaDB", "Nginx", "Raspberry Pi", "systemd"],
    tags: ["full-stack", "web", "security", "self-hosting", "database", "operations"],
    highlights: ["Public recipe browsing and community submission with relational ingredient, step and allergen data.", "Server-side image validation, resizing and WebP conversion.", "Private moderation, CSRF/session hardening, prepared statements, abuse controls and retention policy."],
    evidence: ["The repository includes the application architecture, database schema, security configuration and deployment files.", "Twenty-six optimized recipe images are present.", "A recruiter-facing live deployment is available."],
    repository: "https://github.com/J4ck4b14/LaCocinaDelGroumet",
    live: "https://jam-rb314.tail375004.ts.net/groumet/",
    boundary: "The live deployment runs from personal hardware and its availability may vary; it is a portfolio demonstration rather than a production service.",
    manualRelated: ["fundae-web-series", "graph-calculator"],
    public: true,
  },
  {
    slug: "the-cave",
    title: "The Cave",
    eyebrow: "Adaptive interactive fiction",
    state: "Playable compiled build",
    cardSummary: "An atmospheric cave journey that quietly models pacing, openness, resource use and remembered encounters.",
    summary: "A browser-based interactive-fiction piece built around darkness, carried light, exploration rhythm and subtle player modelling. Later passages and endings adapt to accumulated choices, pacing, openness, resource use and remembered encounters.",
    visual: "narrative",
    visualLabels: ["Observe", "Remember", "Reflect"],
    role: "Sole developer and writer — narrative structure, player model, lighting, audio and presentation.",
    tools: ["Twine", "Twee", "SugarCube", "HTML", "CSS", "JavaScript", "Web Audio"],
    tags: ["narrative", "systems", "player-modeling", "web", "audio", "lighting"],
    highlights: ["101 SugarCube passages with conditional, repeat-aware wandering.", "Candle, darkness, point-light and ambient-transition systems.", "A CaveMirror trait model alters later reflection and exit text from observed behaviour."],
    evidence: ["The project contains 5,882 lines of Twee source.", "A standalone compiled HTML build and 24 audio files are present.", "Passage-history-dependent endings are implemented."],
    boundary: "A public playable URL, concise README and short lighting/audio capture are still missing.",
    repository: "https://github.com/J4ck4b14/TheCave",
    manualRelated: ["dungeon-crawler", "infinity"],
    public: true,
  },
  {
    slug: "fundae-web-series",
    title: "FUNDAE Web Project Series",
    eyebrow: "Cross-stack learning collection",
    state: "Sixteen canonical projects",
    cardSummary: "A progression from web fundamentals to full-stack applications, security and API-quality practice.",
    summary: "A structured series moving from basic HTML, CSS and JavaScript through several backend stacks, then into larger exercises involving MongoDB, REST APIs, authentication, roles, reservations, accessibility, security and implementation-oriented documentation.",
    visual: "collection",
    visualLabels: ["Fundamentals", "Backends", "Applications"],
    role: "Sole developer across all submitted exercises.",
    tools: ["HTML", "CSS", "JavaScript", "Node.js", "Python", "Java", "C#", "PHP", "MongoDB"],
    tags: ["web", "full-stack", "learning", "api", "security", "documentation"],
    highlights: ["Sixteen independent canonical records rather than one undifferentiated bundle.", "Breadth across browser fundamentals, Java, Python, Node, .NET and PHP.", "The strongest later exercises cover relationships, roles, reservations, security and API integration quality."],
    evidence: ["JavaScript syntax checks pass across the static and Node projects.", "The repository checks pass for the veterinary and reservation applications.", "The Flask application passes Python syntax compilation."],
    boundary: "This collection demonstrates progression; it does not replace La Cocina del Groumet as the stronger production full-stack proof point.",
    manualRelated: ["la-cocina-del-groumet", "graph-calculator"],
    children: ["fundae-01-basic-html", "fundae-02-css-styling", "fundae-03-javascript-data", "fundae-04-form-validation", "fundae-05-java-bmi", "fundae-06-flask-tasks", "fundae-07-notes-api", "fundae-08-aspnet-tasks", "fundae-10-semantic-html", "fundae-11-responsive-layout", "fundae-12-gallery-lightbox", "fundae-13-secure-contact", "fundae-14-vet-platform", "fundae-15-oop-showcase", "fundae-16-space-reservations", "fundae-17-api-playbook"],
    public: true,
  },
  {
    slug: "multishooter",
    title: "MultiShooter",
    eyebrow: "Unity multiplayer shooter",
    state: "Playable collaboration — release state unverified",
    cardSummary: "A networked shooter covering local-multiplayer foundations, authoritative gameplay and complete game production.",
    summary: "A Unity multiplayer shooter in which Juan built the shooting, spawning, power-ups, level, lighting, cameras, menu and game design after Alejandro helped establish the local-multiplayer foundation.",
    visual: "network",
    visualLabels: ["Connect", "Authorise", "Synchronise"],
    role: "Primary implementer across gameplay and production; Alejandro is credited for helping establish the local multiplayer base.",
    tools: ["Unity", "C#", "Multiplayer networking", "Real-time lighting"],
    tags: ["multiplayer", "networking", "unity", "gameplay", "shooter"],
    highlights: ["Networked shooting, spawning and power-up systems.", "Level creation, lighting, cameras and menu flow.", "Game-design ownership beyond the initial multiplayer base."],
    evidence: ["Repository history and project structure establish a substantial Unity multiplayer implementation.", "Credits identify Alejandro’s help with the local multiplayer base and Juan’s ownership of the remaining production work.", "A public repository is available."],
    boundary: "Simultaneous host/client footage and exact current release status still need verification.",
    repository: "https://github.com/J4ck4b14/MultiShooter",
    manualRelated: ["fishyfish", "arsenal-ar-card", "return-vector"],
    public: true,
  },
];

const compactSeeds = [
  { slug: "fundae-01-basic-html", title: "Basic HTML", description: "A first structured page using headings, paragraphs, images, links and lists.", tools: ["HTML"], evidence: "Source and four media assets are present.", tags: ["web", "html", "fundamentals"], related: ["fundae-02-css-styling"] },
  { slug: "fundae-02-css-styling", title: "CSS Styling", description: "A focused styling exercise covering typography, colour, margins and positioning.", tools: ["HTML", "CSS"], evidence: "Source is present.", tags: ["web", "css", "fundamentals"], related: ["fundae-11-responsive-layout"] },
  { slug: "fundae-03-javascript-data", title: "JavaScript Data", description: "A small data-and-behaviour exercise using primitive variables, an object, an interests array and functions.", tools: ["HTML", "CSS", "JavaScript"], evidence: "Source is present.", tags: ["web", "javascript", "fundamentals"] },
  { slug: "fundae-04-form-validation", title: "Form Validation", description: "A browser form with field and format validation, accompanied by explicit test cases.", tools: ["HTML", "CSS", "JavaScript"], evidence: "Source and TEST_CASES.md are present.", tags: ["web", "javascript", "testing", "forms"], related: ["fundae-13-secure-contact"] },
  { slug: "fundae-05-java-bmi", title: "Java Servlet/JSP BMI Calculator", description: "A server-rendered BMI calculator with POST handling, JSP presentation and session-backed history.", tools: ["Java 17", "Jakarta Servlet", "JSP", "Maven", "Tomcat"], evidence: "Source and build configuration are present.", tags: ["web", "java", "backend"] },
  { slug: "fundae-06-flask-tasks", title: "Flask Task List", description: "An in-memory task list with two default tasks and a small Flask-rendered interface.", tools: ["Python", "Flask", "HTML", "CSS"], evidence: "Python syntax compilation passed.", tags: ["web", "python", "backend"] },
  { slug: "fundae-07-notes-api", title: "Express Notes API", description: "A REST service providing GET, POST, PUT and DELETE note operations while serving a static frontend.", tools: ["Node.js", "Express", "HTML", "CSS", "JavaScript"], evidence: "JavaScript syntax checks passed.", tags: ["web", "node", "api", "backend"] },
  { slug: "fundae-08-aspnet-tasks", title: "ASP.NET Core Task List", description: "A CRUD task application implemented with ASP.NET Core Minimal APIs and a browser frontend.", tools: ["C#", ".NET 8", "ASP.NET Core", "HTML", "CSS", "JavaScript"], evidence: "Source is present; a fresh runtime verification remains pending.", tags: ["web", "csharp", "api", "backend"] },
  { slug: "fundae-10-semantic-html", title: "Semantic HTML", description: "A page structured with header, navigation, main, articles, aside and footer landmarks.", tools: ["HTML", "CSS"], evidence: "Source is present.", tags: ["web", "html", "accessibility"] },
  { slug: "fundae-11-responsive-layout", title: "Responsive Flex/Grid", description: "A responsive layout exercise combining Flexbox, CSS Grid and four breakpoints.", tools: ["HTML", "CSS"], evidence: "Source is present.", tags: ["web", "css", "responsive"] },
  { slug: "fundae-12-gallery-lightbox", title: "Image Gallery & Lightbox", description: "Two image galleries with a modal lightbox, navigation controls, transitions and animation.", tools: ["HTML", "CSS", "JavaScript"], evidence: "Eight media assets are present and JavaScript syntax checks passed.", tags: ["web", "javascript", "interaction"] },
  { slug: "fundae-13-secure-contact", title: "Secure PHP Contact Form", description: "An accessible contact form with server validation, CSRF protection, a honeypot and environment-based configuration.", tools: ["PHP", "HTML", "CSS"], evidence: "Source is present; PHP execution was unavailable.", tags: ["web", "php", "security", "forms"] },
  { slug: "fundae-14-vet-platform", title: "Veterinary Consultation Platform", description: "A full-stack consultation manager modelling owners, animals and consultations with REST routes and MongoDB relationships.", tools: ["Node.js", "Express", "MongoDB", "Mongoose", "HTML", "CSS", "JavaScript"], evidence: "The repository syntax-check command passes.", tags: ["web", "node", "mongodb", "full-stack", "api"] },
  { slug: "fundae-15-oop-showcase", title: "OOP Learning Showcase", description: "A browser showcase demonstrating inheritance, polymorphism and reusable rendering through a small artefact hierarchy.", tools: ["HTML", "CSS", "JavaScript"], evidence: "JavaScript syntax checks passed.", tags: ["web", "javascript", "oop"] },
  { slug: "fundae-16-space-reservations", title: "Space Reservation Platform", description: "A role-aware reservation system with overlap prevention, user administration, persistent sessions and security middleware.", tools: ["Node.js", "Express", "MongoDB", "Mongoose", "EJS", "bcrypt", "Helmet"], evidence: "The repository syntax-check command passes.", tags: ["web", "node", "mongodb", "security", "full-stack"] },
  { slug: "fundae-17-api-playbook", title: "Frontend API Integration & Quality Playbook", description: "An implementation-oriented guide covering contracts, consumption, errors, UI state, sessions, security and testing.", tools: ["HTML", "CSS", "JavaScript", "Technical writing"], evidence: "Source is present and JavaScript checks passed.", tags: ["web", "api", "documentation", "testing"] },
];

// Supporting exercises use the same page renderer, but stay deliberately
// compact so they show progression without competing with flagship work.
const compactProjects = compactSeeds.map((seed) => ({
  slug: seed.slug,
  title: seed.title,
  eyebrow: "FUNDAE learning project",
  state: "Canonical supporting record",
  cardSummary: seed.description,
  summary: seed.description,
  visual: "collection",
  visualLabels: [seed.tools[0] ?? "Learn", seed.tools[1] ?? "Build", "Verify"],
  role: "Solo learning project.",
  tools: seed.tools,
  tags: [...seed.tags, "fundae"],
  highlights: [seed.description],
  evidence: [seed.evidence],
  boundary: "This is intentionally a compact progression record, not a flagship portfolio claim.",
  manualRelated: seed.related ?? ["fundae-web-series"],
  compact: true,
  public: true,
}));

// A slug-indexed map keeps route lookups predictable and prevents page content
// from being duplicated across recruiter profiles.
const projects = Object.fromEntries(
  [...majorProjects, ...compactProjects].map((project) => [project.slug, project]),
);

function getProject(slug) {
  return projects[slug];
}


function getRelatedProjects(project, limit = 3) {
  // Curated relationships come first. Remaining slots are filled by shared
  // tags, with title order used only to keep equal scores deterministic.
  const candidates = Object.values(projects).filter((candidate) => candidate.public && candidate.slug !== project.slug);
  const manual = (project.manualRelated ?? []).map(getProject).filter((candidate) => Boolean(candidate?.public));
  const used = new Set(manual.map((candidate) => candidate.slug));
  const ranked = candidates
    .filter((candidate) => !used.has(candidate.slug))
    .map((candidate) => ({ candidate, score: candidate.tags.filter((tag) => project.tags.includes(tag)).length }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score || a.candidate.title.localeCompare(b.candidate.title))
    .map(({ candidate }) => candidate);
  return [...manual, ...ranked].slice(0, limit);
}

window.PORTFOLIO_DATA = { projects, getProject, getRelatedProjects };
